name: Conda package

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  build_windows:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        python: ['3.11']
        runner: ["windows-2022", "windows-2019"]

    continue-on-error: true

    env:
      conda-bld: C:\Miniconda\conda-bld\win-64\

    steps:
      - uses: actions/checkout@v4.1.5
        with:
          fetch-depth: 0

      - name: Build simple executable
        run: |
           cd simple
           cmake . -B build -DCMAKE_INSTALL_PREFIX=.
           cmake --build build --target install

      - name: Run simple executable
        run: |
           cd simple
           ls
           /bin/simple_c.exe
           /bin/simple_cxx.exe

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: latest
          conda-build-version: "*"
          activate-environment: test
          channels: conda-forge

      - name: List environment
        run: conda list -n base
      
      - name: Build conda package
        run: conda build --python ${{ matrix.python }} -c conda-forge --override-channels conda-recipe

